### ISSUE TITLE
Compatible L5.2?

### ISSUE THREAD

**Issue by michel3vb** [skydiver/laravel-route-blocker#1]
Hi,

Is this package compatible with L5.2?

Michel

**Comment by skydiver** [comment]
Sorry, no right now.

I will take a look for a possible upgrade in the next days...

**Comment by skydiver** [comment]
Hello @michel3vb,

I've added support for Laravel 5.2

Thanks.-

**Comment by michel3vb** [comment]
Thanks @skydiver
