### ISSUE TITLE
Possibility of opposite? Block by blacklist?

### ISSUE THREAD

**Issue by kingsloi** [skydiver/laravel-route-blocker#12]
Hey, 

Looks like a great package! I haven't check it out yet, but it wasn't clear by the docs, is it possible to block groups of IPs, and allow everything else?

I like laravel-firewall but it's a bit too complex for my needs, this seems perfect. 

Cheers

**Comment by Sarfroz** [comment]
i tried to made what you asked and it worked like a charm here it is

`    public function handle($request, Closure $next, $group) {

        $allow = config('laravel-route-blocker.whitelist.' . $group);
        $ip    = $request->getClientIp();

        // SEARCH IN WHITELIST
        if (is_array($allow)) {
            foreach ($allow as $addr) {
                if (str_is($addr, $ip)) { // match ip found then abort
                    abort(config('laravel-route-blocker.response_status'), config('laravel-route-blocker.response_message'));
                    //return $next($request);
                }
            }
        }
        return $next($request);
        // REDIRECT OR THROW ERROR
        //if (config('laravel-route-blocker.redirect_to') && filter_var(config('laravel-route-blocker.redirect_to'), FILTER_VALIDATE_URL)) {
        //    return redirect()->to(config('laravel-route-blocker.redirect_to'));
        //} else {
        //    abort(config('laravel-route-blocker.response_status'), config('laravel-route-blocker.response_message'));
        //}

    }`

**Comment by skydiver** [comment]
hello @Sarfroz 

do you wanna send a PR with the feature?


Thanks.-

**Comment by skydiver** [comment]
After more than 2 years, this feature will be added on version 1.5.0 😃
