### ISSUE TITLE
question: do you handle different types of IP addresses?

### ISSUE THREAD

**Issue by armyofda12mnkeys** [skydiver/laravel-route-blocker#13]
I saw this was inspired by antonioribeiro/firewall package.
Can you use IP addresses like that package:
'blacklist' => array(
    '127.0.0.1',
    '192.168.17.0/24'
    '127.0.0.1/255.255.255.255'
    '10.0.0.1-10.0.0.255'
    '172.17.*.*'
),

Im particularly interested in the 192.168.17.0/24 format since thats how the network admins usually send whitelists/blacklist ip ranges to me.

Also Im curious, in your opinion, what is the advantages and disadvantages of using this plugin vs antonioribeiro/firewall  package?

**Comment by skydiver** [comment]
I know i'm replying almost 5 months later but i wanna leave a message for future reference.

I'm not sure the current state of `antonioribeiro/firewall` but i can imagine has more features than this package.

`laravel-route-blocker` was needed a few years ago for a previous work, but don't remember what wasn't available on the other package at the time 🤷‍♂️
