### ISSUE TITLE
Country block?

### ISSUE THREAD

**Issue by robertnicjoo** [skydiver/laravel-route-blocker#17]
Hi,
How do you block total country ip?
Example: I don't want anyone from x country have access to my website. Or yet better i want only put one country in my whitelist and the rest of the world be banned?

**Comment by jamgerona** [comment]
how to change the client ip of this library to server ip?

i need to change it to server ip

**Comment by skydiver** [comment]
This package can't can't block countries IPs
There are plenty of other tools to make this (of course, a PR is always welcome).
