### ISSUE TITLE
laravel-route-blocker seems not compatible with laravel 6.6.2

### ISSUE THREAD

**Issue by JulianFo7** [skydiver/laravel-route-blocker#21]
conflicts with laravel/framework[v6.6.2]

    - don't install illuminate/support v5.8.34|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.8.35|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.8.36|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.8.4|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.8.8|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.8.9|don't install laravel/framework v6.6.2
    - Installation request for laravel/framework (locked at v6.6.2, required as ^6.2) -> satisfiable by laravel/framework[v6.6.2].

**Comment by skydiver** [comment]
Hello @JulianFo7 

This is strange, i was able to install, these where my steps:

* `composer create-project laravel/laravel new-laravel6-app "6.*"`
* `composer require skydiver/laravel-route-blocker`

Tested using `Laravel Framework 6.18.16`

**Comment by JulianFo7** [comment]
Hello,


Can we use the current projet and then adding the laravel-route-blocker ?
Or, must to create  a new & dedicated project ?

Rgds,

Fwad

De : Martin M.<mailto:notifications@github.com>
Envoyé le :lundi 1 juin 2020 14:59
À : skydiver/laravel-route-blocker<mailto:laravel-route-blocker@noreply.github.com>
Cc : JulianFo7<mailto:fwaad@hotmail.com>; Mention<mailto:mention@noreply.github.com>
Objet :Re: [skydiver/laravel-route-blocker] laravel-route-blocker seems not compatible with laravel 6.6.2 (#21)


Hello @JulianFo7<https://github.com/JulianFo7>

This is strange, i was able to install, these where my steps:

  *   composer create-project laravel/laravel new-laravel6-app "6.*"
  *   composer require skydiver/laravel-route-blocker

Tested using Laravel Framework 6.18.16

**Comment by JulianFo7** [comment]
This is the fully output we got :

/var/www/loop/projectAT/tro_op$ composer require skydiver/laravel-route-blocker
Using version ^1.4 for skydiver/laravel-route-blocker
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install dawson/youtube 4.3.1
    - Conclusion: remove laravel/framework v6.6.2
    - Installation request for dawson/youtube ^4.3 -> satisfiable by dawson/youtube[4.3, 4.3.1].
    - Conclusion: don't install laravel/framework v6.6.2
    - dawson/youtube 4.3 requires illuminate/support ^5.4 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.36, v5.8.4, v5.8.8, v5.8.9].
    - illuminate/support 5.4.x-dev conflicts with laravel/framework[v6.6.2].
    - illuminate/support 5.5.x-dev conflicts with laravel/framework[v6.6.2].
    - illuminate/support v5.4.0 conflicts with laravel/framework[v6.6.2].
    - illuminate/support v5.4.13 conflicts with laravel/framework[v6.6.2].
    - illuminate/support v5.4.17 conflicts with laravel/framework[v6.6.2].
    - illuminate/support v5.4.19 conflicts with laravel/framework[v6.6.2].
    - illuminate/support v5.4.27 conflicts with laravel/framework[v6.6.2].
    - illuminate/support v5.4.36 conflicts with laravel/framework[v6.6.2].
    - illuminate/support v5.4.9 conflicts with laravel/framework[v6.6.2].
    - illuminate/support v5.5.0 conflicts with laravel/framework[v6.6.2].
    - illuminate/support v5.5.16 conflicts with laravel/framework[v6.6.2].
    - illuminate/support v5.5.17 conflicts with laravel/framework[v6.6.2].
    - illuminate/support v5.5.2 conflicts with laravel/framework[v6.6.2].
    - illuminate/support v5.5.28 conflicts with laravel/framework[v6.6.2].
    - illuminate/support v5.5.35 conflicts with laravel/framework[v6.6.2].
    - illuminate/support v5.5.36 conflicts with laravel/framework[v6.6.2].
    - illuminate/support v5.5.37 conflicts with laravel/framework[v6.6.2].
    - illuminate/support v5.5.39 conflicts with laravel/framework[v6.6.2].
    - illuminate/support v5.5.40 conflicts with laravel/framework[v6.6.2].
    - illuminate/support v5.5.41 conflicts with laravel/framework[v6.6.2].
    - illuminate/support v5.5.43 conflicts with laravel/framework[v6.6.2].
    - illuminate/support v5.5.44 conflicts with laravel/framework[v6.6.2].
    - illuminate/support v5.6.4 conflicts with laravel/framework[v6.6.2].
    - illuminate/support v5.6.5 conflicts with laravel/framework[v6.6.2].
    - illuminate/support v5.6.6 conflicts with laravel/framework[v6.6.2].
    - illuminate/support v5.6.7 conflicts with laravel/framework[v6.6.2].
    - don't install illuminate/support v5.5.33|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.5.34|don't install laravel/framework v6.6.2
    - don't install illuminate/support 5.6.x-dev|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.6.0|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.6.1|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.6.10|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.6.11|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.6.12|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.6.13|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.6.14|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.6.15|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.6.16|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.6.17|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.6.19|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.6.2|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.6.20|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.6.21|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.6.22|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.6.23|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.6.24|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.6.25|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.6.26|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.6.27|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.6.28|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.6.29|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.6.3|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.6.30|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.6.31|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.6.32|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.6.33|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.6.34|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.6.35|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.6.36|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.6.37|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.6.38|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.6.39|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.6.8|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.6.9|don't install laravel/framework v6.6.2
    - don't install illuminate/support 5.7.17|don't install laravel/framework v6.6.2
    - don't install illuminate/support 5.7.18|don't install laravel/framework v6.6.2
    - don't install illuminate/support 5.7.19|don't install laravel/framework v6.6.2
    - don't install illuminate/support 5.7.x-dev|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.7.0|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.7.1|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.7.10|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.7.11|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.7.15|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.7.2|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.7.20|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.7.21|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.7.22|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.7.23|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.7.26|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.7.27|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.7.28|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.7.3|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.7.4|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.7.5|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.7.6|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.7.7|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.7.8|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.7.9|don't install laravel/framework v6.6.2
    - don't install illuminate/support 5.8.x-dev|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.8.0|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.8.11|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.8.12|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.8.14|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.8.15|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.8.17|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.8.18|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.8.19|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.8.2|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.8.20|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.8.22|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.8.24|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.8.27|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.8.28|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.8.29|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.8.3|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.8.30|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.8.31|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.8.32|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.8.33|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.8.34|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.8.35|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.8.36|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.8.4|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.8.8|don't install laravel/framework v6.6.2
    - don't install illuminate/support v5.8.9|don't install laravel/framework v6.6.2
    - Installation request for laravel/framework (locked at v6.6.2, required as ^6.2) -> satisfiable by laravel/framework[v6.6.2].



De : Martin M.<mailto:notifications@github.com>
Envoyé le :lundi 1 juin 2020 14:59
À : skydiver/laravel-route-blocker<mailto:laravel-route-blocker@noreply.github.com>
Cc : JulianFo7<mailto:fwaad@hotmail.com>; Mention<mailto:mention@noreply.github.com>
Objet :Re: [skydiver/laravel-route-blocker] laravel-route-blocker seems not compatible with laravel 6.6.2 (#21)


Hello @JulianFo7<https://github.com/JulianFo7>

This is strange, i was able to install, these where my steps:

  *   composer create-project laravel/laravel new-laravel6-app "6.*"
  *   composer require skydiver/laravel-route-blocker

Tested using Laravel Framework 6.18.16

**Comment by skydiver** [comment]
Hey @JulianFo7 

Should be easy to install this package on an existing project.

From the logs i see the package `dawson/youtube` can't be installed with Laravel 6.

Looking the package repo https://github.com/joedawson/youtube and it seems to be compatible only with Laravel 5.

**Comment by skydiver** [comment]
Also, i've removed the laravel dependency in the upcoming version, 1.5.0

Feel free to test using `composer require skydiver/laravel-route-blocker:dev-release/1.5.0`
